version: '3'

services:
  wdqs-frontend:
    image: wikibase/wdqs-frontend:wmde.11
    ports:
     - 8099:80
    depends_on:
    - wdqs-proxy
    networks:
      default:
        aliases:
         - wdqs-frontend.svc
    environment:
      - WIKIBASE_HOST=www.wikidata.org
      - WDQS_HOST=wdqs-proxy.svc
      - WDQS_PORT=80
      - BRAND_TITLE=Private Wikidata Query
  wdqs:
    image: wikibase/wdqs:0.3.97-wmde.8
    volumes:
      - ./data:/wdqs/data
      - ./sources:/sources
    command: /runBlazegraph.sh
    networks:
      default:
        aliases:
         - wdqs.svc
    environment:
      - WIKIBASE_HOST=www.wikidata.org
      - WDQS_HOST=wdqs.svc
      - WDQS_PORT=9999
      - HEAP_SIZE=224g
      - BLAZEGRAPH_EXTRA_OPTS=-Xms224g
    ports:
      - "9999:9999"
  wdqs-proxy:
    image: caddy
    restart: unless-stopped
    environment:
     - PROXY_PASS_HOST=wdqs.svc:9999
    volumes:
     - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
     - 80
    depends_on:
    - wdqs
    networks:
      default:
        aliases:
         - wdqs-proxy.svc
